plugins {
	id "java"
	id "org.springframework.boot"
	id "org.springframework.aot.smoke-test"
	id "org.graalvm.buildtools.native"
}

def springDataVersion = "4.2.0-SNAPSHOT"
def springDataCommonsVersion = "4.2.0-SNAPSHOT"
def hibernateVersion = "8.0.0-SNAPSHOT"
def jakartaPersistenceVersion = "4.0.0-M6"

repositories {
	mavenLocal {
		content {
			includeGroup "org.springframework.data"
			includeGroup "org.hibernate.orm"
			includeGroup "jakarta.persistence"
		}
	}
	maven {
		name = "Sonatype Central Snapshots"
		url = "https://central.sonatype.com/repository/maven-snapshots"
		mavenContent {
			snapshotsOnly()
		}
		content {
			includeGroup "org.hibernate.orm"
			includeGroup "jakarta.persistence"
		}
	}
}

configurations.all {
	resolutionStrategy.eachDependency { details ->
		def requested = details.requested
		if (requested.group == "org.springframework.data" && requested.name == "spring-data-jpa") {
			details.useVersion(springDataVersion)
		}
		else if (requested.group == "org.springframework.data" && requested.name == "spring-data-commons") {
			details.useVersion(springDataCommonsVersion)
		}
		else if (requested.group == "org.hibernate.orm") {
			details.useVersion(hibernateVersion)
		}
		else if (requested.group == "jakarta.persistence" && requested.name == "jakarta.persistence-api") {
			details.useVersion(jakartaPersistenceVersion)
		}
	}
}

dependencies {
	implementation(enforcedPlatform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES))
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")

	runtimeOnly("com.h2database:h2")

	testImplementation("org.springframework.boot:spring-boot-starter-data-jpa-test")

	appTestImplementation(project(":aot-smoke-test-support"))
	appTestImplementation("org.awaitility:awaitility:4.2.0")
}
