create table author
(
    id   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL
);

create table book
(
    id     serial PRIMARY KEY,
    author integer NOT NULL REFERENCES author (id),
    title  varchar NOT NULL
);
