name: 3.4.x | Data Smoke Tests | Data Jpa Kotlin
on:
  workflow_run:
    workflows: ["3.4.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  data_jpa_kotlin_app_test:
    name: Data Jpa Kotlin App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: data:data-jpa-kotlin
      task: appTest
  data_jpa_kotlin_native_app_test:
    name: Data Jpa Kotlin Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: data:data-jpa-kotlin
      task: nativeAppTest
