name: 3.4.x | Framework Smoke Tests | Webmvc Tomcat Tls
on:
  workflow_run:
    workflows: ["3.4.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  webmvc_tomcat_tls_app_test:
    name: Webmvc Tomcat Tls App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: framework:webmvc-tomcat-tls
      task: appTest
  webmvc_tomcat_tls_native_app_test:
    name: Webmvc Tomcat Tls Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: framework:webmvc-tomcat-tls
      task: nativeAppTest
