name: 3.4.x | Boot Smoke Tests | Conditional
on:
  workflow_run:
    workflows: ["3.4.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  conditional_app_test:
    name: Conditional App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: boot:conditional
      task: appTest
  conditional_native_app_test:
    name: Conditional Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.4.x
      project: boot:conditional
      task: nativeAppTest
