name: 3.5.x | Cloud Smoke Tests | Cloud Stream Rabbit
on:
  workflow_run:
    workflows: ["3.5.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  cloud_stream_rabbit_app_test:
    name: Cloud Stream Rabbit App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: cloud:cloud-stream-rabbit
      task: appTest
  cloud_stream_rabbit_native_app_test:
    name: Cloud Stream Rabbit Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: cloud:cloud-stream-rabbit
      task: nativeAppTest
