name: 3.5.x | Boot Smoke Tests | Xml Config
on:
  workflow_run:
    workflows: ["3.5.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  xml_config_app_test:
    name: Xml Config App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: boot:xml-config
      task: appTest
  xml_config_native_app_test:
    name: Xml Config Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: boot:xml-config
      task: nativeAppTest
