name: 3.5.x | Graphql Smoke Tests | Graphql Webflux
on:
  workflow_run:
    workflows: ["3.5.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  graphql_webflux_app_test:
    name: Graphql Webflux App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: graphql:graphql-webflux
      task: appTest
  graphql_webflux_native_app_test:
    name: Graphql Webflux Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: graphql:graphql-webflux
      task: nativeAppTest
  graphql_webflux_test:
    name: Graphql Webflux Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: graphql:graphql-webflux
      task: test
  graphql_webflux_native_test:
    name: Graphql Webflux Native Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: graphql:graphql-webflux
      task: nativeTest
