name: 3.5.x | Framework Smoke Tests | Webflux Netty Tls
on:
  workflow_run:
    workflows: ["3.5.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  webflux_netty_tls_app_test:
    name: Webflux Netty Tls App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: framework:webflux-netty-tls
      task: appTest
  webflux_netty_tls_native_app_test:
    name: Webflux Netty Tls Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: framework:webflux-netty-tls
      task: nativeAppTest
