name: 3.5.x | Boot Smoke Tests | Configuration Properties
on:
  workflow_run:
    workflows: ["3.5.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  configuration_properties_app_test:
    name: Configuration Properties App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: boot:configuration-properties
      task: appTest
  configuration_properties_native_app_test:
    name: Configuration Properties Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 3.5.x
      project: boot:configuration-properties
      task: nativeAppTest
