name: 4.0.x | Security Smoke Tests | Security Webmvc
on:
  workflow_run:
    workflows: ["4.0.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  security_webmvc_app_test:
    name: Security Webmvc App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: security:security-webmvc
      task: appTest
  security_webmvc_native_app_test:
    name: Security Webmvc Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: security:security-webmvc
      task: nativeAppTest
      graal_version: 25
