name: 4.0.x | Data Smoke Tests | Data Redis
on:
  workflow_run:
    workflows: ["4.0.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  data_redis_app_test:
    name: Data Redis App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: data:data-redis
      task: appTest
  data_redis_native_app_test:
    name: Data Redis Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: data:data-redis
      task: nativeAppTest
      graal_version: 25
