name: 4.0.x | Integration Smoke Tests | Spring Kafka
on:
  workflow_run:
    workflows: ["4.0.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  spring_kafka_app_test:
    name: Spring Kafka App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: integration:spring-kafka
      task: appTest
  spring_kafka_native_app_test:
    name: Spring Kafka Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: integration:spring-kafka
      task: nativeAppTest
      graal_version: 25
