name: 4.0.x | Boot Smoke Tests | Mustache Webflux
on:
  workflow_run:
    workflows: ["4.0.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  mustache_webflux_app_test:
    name: Mustache Webflux App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: boot:mustache-webflux
      task: appTest
  mustache_webflux_native_app_test:
    name: Mustache Webflux Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: boot:mustache-webflux
      task: nativeAppTest
      graal_version: 25
