name: 4.0.x | Framework Smoke Tests | Webmvc Tomcat
on:
  workflow_run:
    workflows: ["4.0.x | Warm Caches"]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  webmvc_tomcat_app_test:
    name: Webmvc Tomcat App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: framework:webmvc-tomcat
      task: appTest
  webmvc_tomcat_native_app_test:
    name: Webmvc Tomcat Native App Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: framework:webmvc-tomcat
      task: nativeAppTest
      graal_version: 25
  webmvc_tomcat_test:
    name: Webmvc Tomcat Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: framework:webmvc-tomcat
      task: test
  webmvc_tomcat_native_test:
    name: Webmvc Tomcat Native Test
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      checkout_repository: spring-projects/spring-aot-smoke-tests
      checkout_ref: 4.0.x
      project: framework:webmvc-tomcat
      task: nativeTest
      graal_version: 25
